export const SET_CYCLE_START_TIME = 'SET_CYCLE_START_TIME';
export const SET_TRIAL_START_TIME = 'SET_TRIAL_START_TIME';
export const SET_SOUND_TIME = 'SET_SOUND_TIME';
export const SET_USER_REACT_TIME = 'SET_USER_REACT_TIME';

export const SET_ROUND_ACTIVE_TRUE = 'SET_ROUND_ACTIVE_TRUE';
export const SET_ROUND_ACTIVE_FALSE = 'SET_ROUND_ACTIVE_FALSE';

export const SET_SELF_CATCH_PRESSED_TRUE = 'SET_SELF_CATCH_PRESSED_TRUE';
export const SET_SELF_CATCH_PRESSED_FALSE = 'SET_SELF_CATCH_PRESSED_FALSE';
export const SET_CONFIRM_DONE_PRESSED_TRUE = 'SET_CONFIRM_DONE_PRESSED_TRUE';
export const SET_CONFIRM_DONE_PRESSED_FALSE = 'SET_CONFIRM_DONE_PRESSED_FALSE';

export const INC_GAME_COUNT = 'INC_GAME_COUNT';
export const INC_USER_COUNT = 'USER_GAME_COUNT';
export const RESET_GAME_COUNT = 'RESET_GAME_COUNT';
export const RESET_USER_COUNT = 'RESET_USER_COUNT';

export const START_BLOCK_TIMER = 'START_BLOCK_TIMER';
export const TICK_BLOCK_TIMER = 'TICK_BLOCK_TIMER'
export const STOP_BLOCK_TIMER = 'STOP_BLOCK_TIMER';

export const STORE_ID = 'STORE_ID';

export const DEC_BREAK_COUNT = 'DEC_BREAK_COUNT';