export const SET_CYCLE_START_TIME = 'SET_CYCLE_START_TIME';
export const SET_TRIAL_START_TIME = 'SET_TRIAL_START_TIME';
export const SET_SOUND_TIME = 'SET_SOUND_TIME';
export const SET_USER_REACT_TIME = 'SET_USER_REACT_TIME';